from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import json
from pathlib import Path

# Creates a web application instance
app = FastAPI(title="Market Shock Intelligence System API")

# Allow frontend to access backend (important later)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Finds the project root reliably
BASE_DIR = Path(__file__).resolve().parent.parent
OUTPUTS_DIR = BASE_DIR / "outputs"

@app.get("/")
def root():
    return {"message": "MSIS API is running"}

# When someone visits /regimes, run this function
@app.get("/regimes")
def get_regimes():
    """
    Returns market regime data generated by ML Model 1
    """
    file_path = OUTPUTS_DIR / "regimes.json"

    with open(file_path, "r") as f:
        # Loads ML output exactly as generated
        data = json.load(f)

    return data
